/* THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT. */
/* See the input xml in cfg/sample-blink.cfg */

#ifndef __CONFIG_H
#define __CONFIG_H

#include <vm.h>

#include <arch.h>

#include <hypercall_defines.h>

/* Debug UART prints */
#define WARNINGS
#define INFOS
#define ERRORS

/* Hypervisor kernel configuration */
#define MILISECOND ((CPU_FREQ/2)/ 1000)
#define UART_SPEED 115200
#define QUANTUM_SCHEDULER_MS 10 
#define GUEST_QUANTUM_MS 1 

/* VMs mapping */
static const struct vmconf_t const VMCONF[] = {
	{ /* VM#1 */
		vm_name: "blink",
		os_type: BARE_METAL,
		priority: 100,
		num_tlb_entries: 0x1,
		tlb: (const struct tlb_entries const []){
			{
				entrylo0: 0x00040,
				entrylo1: 0x00044,
				pagemask: PAGEMASK_16KB,
				entryhi: 0x00000,
				coherency: WRITE_BACK
			},
		},
		ram_base: 0x80040000,
	},
};

/* Virtual Machine names: blink  */
#define NVMACHINES 1

#endif

